name: release
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build PDF
        uses: docker://sphinxdoc/sphinx-latexpdf
        with:
          args: make latexpdf
        env:
          LANG: C.UTF-8

      - name: Archive PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: index.pdf
          path: build/latex/testproject.pdf

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: index.pdf
      
      - name: Display structure of downloaded files
        run: ls -R
