name: release
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
    
      - name: Build PDF
        uses: docker://sphinxdoc/sphinx-latexpdf
        with:
          args: sphinx-build -M latexpdf source build
        env:
          LANG: C.UTF-8
          SPHINXOPTS: -t pdf
      
      - name: Archive PDF artifacts
        uses: actions/upload-artifact@v2
        with:
          name: index.pdf
          path: build/latex/index.pdf
